#!/usr/bin/env node

import { run } from "node:test";
import * as reporter from "node:test/reporters";
import * as path from "node:path";
import * as fs from "node:fs";
import * as url from "node:url";
import { finished } from "node:stream";

const __dirname = url.fileURLToPath(new URL(".", import.meta.url));

void (async function () {
  let files = await findTests(path.join(__dirname, "src"));

  // Filter by arguments
  if (process.argv.slice(2).length) {
    files = files.filter((testFile) =>
      process.argv
        .slice(2)
        .find(
          (filter) =>
            path
              .basename(testFile)
              .replace(`.test${path.extname(testFile)}`, "") === filter,
        ),
    );
  }

  const test_stream = run({
    files,
  })
    .on('test:fail', () => {
      process.exitCode = 1
    })
    .compose(new reporter.spec())

  test_stream.pipe(process.stdout)
  await new Promise((res) => finished(test_stream, res))
})();

async function findTests(dir: string = "."): Promise<Array<string>> {
  const results: string[] = [];

  async function scan(currentDir: string): Promise<void> {
    const entries = await fs.promises.readdir(currentDir, {
      withFileTypes: true,
    });

    for (const entry of entries) {
      const fullPath = path.join(currentDir, entry.name);

      if (entry.isDirectory()) {
        await scan(fullPath);
      } else if (
        entry.isFile() &&
        (entry.name.endsWith(".test.mts") ||
          // entry.name.endsWith(".test.ts") ||
          entry.name.endsWith(".test.cts") ||
          entry.name.endsWith(".test.mjs") ||
          entry.name.endsWith(".test.js") ||
          entry.name.endsWith(".test.cjs"))
      ) {
        results.push(fullPath);
      }
    }
  }

  await scan(dir);
  return results;
}
